# Generated by Django 3.0.4 on 2020-03-22 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200321_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='proff',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
