# Generated by Django 3.0.4 on 2020-03-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='proff',
            name='course',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
