# Generated by Django 3.0.4 on 2020-03-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_proff_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proff',
            name='Dpt',
        ),
    ]
